// this file was generated by the following script:
// ./appli/scripts/configure.sh
#ifndef CPP_CONFIG_H
#define CPP_CONFIG_H
#define CPP_OS_LINUX
#define CPP_SYSTEM_GNU_LINUX_X86_64
#define CPP_ARCHITECTURE_64_BITS
#define CPP_MEMORY_ALIGNMENT 32
#define CPP_DATA_SIZE 8
#define CPP_SSE20_COMPLIANT 1
#define CPP_SSE42_COMPLIANT 1
#define CPP_AVX20_COMPLIANT 1

#endif
